FROM ubuntu

RUN apt update && \ 
    apt install python3 \
                python3-pip \
                tesseract-ocr \
                tesseract-ocr-fra \
                tesseract-ocr-spa -y

WORKDIR /ocr_rest_api

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5002

CMD [ "flask", "--app", "app", "run", "-h", "0.0.0.0", "-p", "5002", "--debug" ]