name: Docker Image CI
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the deployment image
      run: docker build -t ${{ vars.DOCKERHUB_IMAGE_NAME }} .
    
    - name: Login to dockerhub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    - name: Push the image
      run: docker push ${{ vars.DOCKERHUB_IMAGE_NAME }}